on:
    pull_request:
    
jobs:
  
    build_publish_backend:
      runs-on: ubuntu-latest
      environment: production
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Publish the app
        run: dotnet publish -c Release --property:PublishDir=publish # Publish the app to the publish folder of the API project
        working-directory: ./backend # specify where to find the solution file
  
    build_frontend:
      runs-on: ubuntu-latest
      environment: production
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Build the app
        run: npm install && npm run lint && npm run build
        working-directory: ./frontend
  
    